[project]
name = "callme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy>=2.2.6",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true, editable = true }

[tool.mypy]
exclude = [
    "^\\.venv/",
    "^llm_sdk/",
]

[[tool.mypy.overrides]]
module = ["llm_sdk", "llm_sdk.*"]
follow_imports = "skip"

[tool.pytest.ini_options]
pythonpath = ["."]
